### ISSUE TITLE
revamp of "About > The Edition"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/edition-webpages#26]
See GD doc **2020-01-17+24_editionwebpages-notes**

- Change “DCE” or “the Edition” to “Secrets of Craft and Nature in Renaissance France”
- Add info about research essays from Overview of Resources
- Content from the previous “The Text: Overview and About”
- Add select content from “Creation of the Edition”
- Remove “general” in the sentence:
     - “Essays that discuss the general material, historical, and cultural context of Ms. Fr. 640”
- In “Structure of the Edition”
     - “(where it is catalogued as “Recueil de recettes” n.d.).” is not indispensable
     - Add a link to Gallica
     - Check content about this in how-to-use - language is close but not the same. Change so they are different.
- Remove section “Reading and Using the Edition” and add link to How to Use
- Not sure we need first two paragraphs (CAG: I would delete them)
     - NJR: Let’s discuss together - I want to give a reason for why I think some of the content is necessary
- link to credits

**Comment by TillmannTaape** [comment]
latest revised text for Research Essays:

Research Essays explore the text of the manuscript, provide material,
technical, and historical context, and discuss student reconstructions
in the Making and Knowing Laboratory.

**Essays by scholars** on the Making and Knowing Team and invited
experts explore different aspects of Ms. Fr. 640 and its material, technical,
textual, and historical context.

**Essays by students** are products of the Making and Knowing Project laboratory seminars
and courses taught by Project collaborators. The majority addresses historical questions by
combining laboratory work with traditional historical research.

All essays will also be archived in Academic Commons where they can be
downloaded as standalone articles.

The Research Essays are grouped in up to three of seven broad categories:

  - **An Introduction**: introductory resources about the manuscript, the Project, and background information.

  - **The Manuscript, Ms. Fr. 640**: its codicology, palaeography, and probable genesis, its relationship to other genres of writing, and the identity of its anonymous author-practitioner.

  - **The Making and Knowing Laboratory**: hands-on work in the Making and Knowing Laboratory and principles of historical reconstruction.
 
  - **Society and Culture**: historical context of the manuscript in sixteenth-century France and beyond.

  - **Art and Its Making**: materials, making, and meaning of art, and the training of artists.

  - **Knowing Nature**: investigation, manipulation, and exploration of nature in Ms. Fr. 640.

  - **The Making and Knowing Project**: initiatives, pedagogy, methods, personnel, and collaborators.

**Comment by ps2270** [comment]
Revisions:
Start with
**What is the Digital Critical Edition?**
This digital critical edition and English translation of the French manuscript Ms. Fr. 640, held by the Bibliothèque nationale de France (BnF), presents a rich and unique sixteenth-century technical text in French transcription and English translation for the first time, and situates its contents in their material and historical context.

The manuscript provides insights into the material, technical, and intellectual world of the late sixteenth century, and brings a better understanding of how and why nature was investigated, used in art, and collected and appreciated in early modern Europe.

The Making and Knowing Project has created this Edition through a series of collaborative workshops, courses, and conferences that have involved students, craft practitioners, artists, scholars of the humanities and social sciences, natural and computer scientists, and scholar-practitioners from the emerging field of the digital humanities.

**Creation of Secrets of Craft and Nature in Renaissance France**
The creation of _Secrets of Craft and Nature in Renaissance France_ has been the primary goal of the Making and Knowing Project since it was founded in 2014. It presents the culmination of over five years of iterative, collaborative, and interdisciplinary work.

Secrets of Craft and Nature in Renaissance France was developed through a series of  workshops, courses, and conferences:

The first stage of transcription, translation, and encoding of the manuscript was carried out in a series of paleography and text workshops (2014–2018) that brought together graduate students (already in possession of advanced French) to learn to read middle French script through transcription exercises and then through intensive transcription and translation of Ms. Fr. 640.

The manuscript’s encoding explores fourteen semantic categories that the Project deemed meaningful in providing insight into the manuscript: animal, body part, currency, environment, material, measurement, medical, music, personal name, place, plant, profession, sensory, and tool.

Students in the Making and Knowing Project’s laboratory seminars from 2014 to 2018 used the transcriptions and translations to investigate the materials and techniques contained in the manuscript.

VIDEO
These students produced essays that featured their research on texts and objects, as well as their experiments in reconstructing the technical processes and recipes in Ms. Fr. 640. The essays gloss entries in Ms. Fr. 640 and provide contextual information for the manuscript more generally.

The student essays were edited extensively by members of the Making and Knowing Project team, after which scholars participating in annual Working Group Meetings commented upon them. They were edited again in 2019 by the Making and Knowing senior Project team.

The research apparatus of _Secrets of Craft and Nature in Renaissance France_ also includes a collection of research essays authored by Working Group members and invited collaborators that discuss different aspects of the context of Ms. Fr. 640.
DELETE paragraph here: (i.e., In addition, several other features provide assistance to readers, including editorial comments (signalled by a red asterisk in the manuscript text), a glossary (accessible as an option in the drop-down menu within the viewing panes and as a standalone resource), a complete bibliography, and a list of all 930 entries—“recipe” or entry headings (titles) in the manuscript.)
The final component of the creation of Secrets of Craft and Nature in Renaissance France was the prototyping of digital components in digital humanities courses held by the Making and Knowing Project at Columbia University, and the development of the Edition platform by the Project Digital Team and Performant Software Solutions. For more information on making the Edition, see Smith, Making the Edition of Ms. Fr. 640.

**Structure of _Secrets of Craft and Nature in Renaissance France_**
Secrets of Craft and Nature in Renaissance France includes four versions of the manuscript text and a rich critical apparatus.

Parallel viewing panes allow users to compare two of the following components:

a diplomatic (verbatim) transcription of the original French text,
a lightly normalized French transcription (with punctuation and diacritical marks added),
an English translation, and
high-definition images of the manuscript fed directly from Gallica, the BnF’s digital library.
Glossary of terms in the manuscript

Secrets of Craft and Nature also integrates access to the Project’s interpretive resources (also accessible as stand-alone features), including:

Essays that discuss the material, historical, and cultural context of Ms. Fr. 640
In-depth multimedia essays that focus on the laboratory reconstruction of selected manuscript entries
Field notes from laboratory reconstructions of select recipes
Principles of transcription, translation, and encoding
Bibliography of works cited
Editorial and translation comments
Glossary of terms 

**Research Essays**
CONTENT OK FROM HERE ONE.

change standalone to stand-alone

**Comment by ps2270** [comment]
done!
