### ISSUE TITLE
revamp (creation) of "About-overview"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/edition-webpages#45]
See GD doc **2020-01-17+24_editionwebpages-notes**

Similar to Resources - overview, create listing of available resources and link to each of the pages

**Comment by TillmannTaape** [comment]
Sorry I'm confused what's happening here – there is text in the file in the repo, but it's not showing up on staging (which it should if it's in the master branch, no?), so that makes me wonder if that text is supposed to be there.

If so, I'm not sure how you'd like me to edit it – in particular, do you want me to fill in the bulleted lists under the headings, e.g. all the contributors under Credits, and all the sponsors under Sponsors? That would be a lot of text for the overview page. Or are those just notes of things that should be added in the actual pages (e.g. Sponsors page)?

@njr2128 @ps2270 Please advise – just to make sure we're on the same page before I make any changes.

Here is the text that's currently on the about-overview page, for reference:

**Creation of the edition**

This digital critical Edition and English translation of the French
manuscript, Ms. Fr. 640, held by the Bibliothèque nationale de France
(BnF),\[1\] presents a rich and unique sixteenth-century technical text
in French transcription and English translation for the first time, and
situates its contents in their material and historical context. The
manuscript provides important insights into the material, technical, and
intellectual worlds of the late sixteenth century, and brings a better
understanding of how and why nature was investigated, used in art, and
collected and appreciated in early modern Europe. The Making and Knowing
Project has created the Edition through a series of collaborative
workshops, courses, and conferences that have involved students, craft
practitioners, artists, scholars of the humanities and social sciences,
natural and computer scientists, and practitioner-scholars from the
emerging field of the digital humanities.

The first stage of transcription, translation, and encoding of the
manuscript was carried out in a series of paleography and text workshops
(2014-2018) that brought together graduate students (already in
possession of advanced French) to learn to read middle French script
through transcription exercises and then through intensive transcription
and translation of Ms. Fr. 640. Students in the Making and Knowing
Project’s laboratory seminars from 2014 to 2018 used the transcriptions
and translations to investigate the materials and techniques contained
in the manuscript. Vid. 1: M\&K Lab video. These students produced
essays that featured their research on texts and objects, as well as
their experiments in reconstructing Ms. Fr. 640’s processes. The essays
explain entries in Ms. Fr. 640 and provide contextual information for
the manuscript more generally. They can be accessed by clicking the XX
icon next to the relevant entries on the “Folio” pages, or from the
Research and Resources menu. The student essays were edited extensively
by members of the Making and Knowing Project team, after which scholars
participating in the annual Working Group Meeting commented upon them.
They were edited again in 2019 by the Making and Knowing senior
editorial team. The Research apparatus of the Edition also includes
dozens of research essays authored by Working Group members and invited
collaborators that discuss different aspects of the context of Ms. Fr.
640. These essays can be accessed on the Research Essays page. Several
additional features provide assistance to readers, including editorial
comments (signalled by a red asterisk in the manuscript text), a
glossary (accessible as an option in the drop-down menu within the
viewing panes), a complete bibliography, and a list of all 928 “recipe”
or entry headings (titles) in the manuscript. This index of recipes also
allows the reader to explore fourteen categories of encoding that the
Project deemed meaningful in providing insight into the manuscript:
animal, body part, currency, environment, material, measurement,
medical, music, personal name, place, plant, profession, sensory, and
tool. In addition, manuscript entries can be explored through filtering
by twenty-six material and process categories devised by the Project.
These categories and their definitions are listed along the left side of
the Entries page.

The final component of the creation of the Edition was prototyping of
the digital components in digital humanities courses held by the Making
and Knowing Project at Columbia University, and development of the
Edition platform by the Project Digital Team. For more information on
making the Edition, see Smith, “Making the Edition,” ann\_329\_ie\_19.

**About the Making and Knowing Project**

This critical edition of a manuscript held by the Bibliothèque nationale
de France (BnF), catalogued as Ms. Fr. 640, was created through the work
of team members, students, and collaborators of the Making and Knowing
Project.\[2\] The Project, founded in 2014 by Pamela H. Smith, is a
research and pedagogical initiative in the Center for Science and
Society at Columbia University. The Making and Knowing Project explores
the intersections between historical craft making and scientific
knowing. See
[Vid.2](https://drive.google.com/file/d/1eVIGM-dzCAVxZsoHEsCMEzLRrOaBM2y0/view?usp=drivesdk).
Drawing on techniques from both laboratory and archival research as well
as studio practice and digital humanities, the Making and Knowing
Project aims to cross the science/humanities divide. The Edition of Ms.
Fr. 640 can shed light not only on what kind of knowledge the
manuscript’s anonymous author possessed about techniques and
materials, but also, more broadly, how the work of *making* was related
to *knowing*. Indeed, the overarching theme of the Project and its work
on the Edition has been to show the ways in which *making is an
epistemic activity*, or, in other words, a form of knowing, rather than
simply an applied form of a higher type of knowledge.

  - > For more information, see <https://www.makingandknowing.org/>.

**Peer review**

This Edition and its research apparatus have been created collectively,
and have been the objects of intense collective review, discussion, and
iterated examination and revision. Because of its format and extensive
scope—three versions of the manuscript and more than 100 research
essays—it was not sent out for peer review. Instead, a form of “open
review” was instituted: each of the student essays was edited at least
three times by different members of the Making and Knowing Team and then
read and commented upon by a scholar within whose expertise the subject
of the essay fell. After this, students had an opportunity to revise the
essay, and, finally, the essay was edited in a final editorial campaign
by the Making and Knowing Team (Clément Godbarge, Pamela Smith, Tillmann
Taape, Tianna Uchacz). The essays authored by invited scholars were
workshopped among all authors at a collective co-writing workshop in
2019, and also underwent editorial review by Making and Knowing team
members. For more information on open review see,
<http://mcpress.media-commons.org/open-review/files/2012/06/MediaCommons_Open_Review_White_Paper_final.pdf>.

The extremely diverse and often obscure materials and techniques treated
in the essays would have presented a problem for conventional peer
review because a large number of reviewers with diverse areas of
expertise would have been needed. Instead, critical oversight was built
into the annual Working Group Meeting, when scholars were selected for
their expertise in the subjects of the essays produced in a given year,
and were assigned a number of essays, commenting formally on the essays
in the three-day meeting. The Project also wished to build into the
collaborative structure the opportunity presented by this intriguing
primary source for students to interact around substantive questions
with accomplished scholars. This was achieved in the process of review
and critique at the annual Working Group Meetings. The Project believes
this solution not only succeeded in integrating phases of pedagogy and
research in an extremely productive manner and provided valuable
opportunities for graduate students, but also resulted in a more
thorough (and pedagogically useful) review of the diverse contents of
the essays than might have been provided by conventional methods of peer
review.

While no method of peer review is foolproof, the Project believes that
its process of review and revision maintained quality and consistency in
its expansive research apparatus. As the practice of historical
scholarship changes, whether through collective research and authorship
or through new approaches such as digital methods and laboratory
research on historical questions, it seems necessary for the practices
and parameters for scholarly peer review also to evolve.

**People and** **Credits**

  - > The Making and Knowing Project strives to adhere to the guidelines
    > for crediting formulated by the Off the Tracks Project:
    > <http://mcpress.media-commons.org/offthetracks/part-one-models-for-collaboration-career-paths-acquiring-institutional-support-and-transformation-in-the-field/a-collaboration/collaborators%e2%80%99-bill-of-rights/>

  - > Restate the official bibliographic credit line

  - > Project team and staff (present and past)
    
      - > Project director
    
      - > Project assistant director
    
      - > Postdocs
    
      - > Senior Editorial Team
    
      - > Project assistants
    
      - > Digital lead & designer-developers
    
      - > Project managers
    
      - > Programming assistants
    
      - > Teaching and lab assistants & guest lecturers
    
      - > Interns
    
      - 
  - > Text workshops

  - > Lab class

  - > Digital lab class
    
      - > Co-instructors, TAs, CGUI

  - > External collaborators
    
      - > WGM attendees
    
      - > Other collaborators

  - > Intro essay writers

  - > CU Library staff

**contact**

**sponsors**

  - > NSF, NEH, Luce, Collaboratory, etc.

**How to cite**

  - > The edition

  - > Assets from academic commons

**How to use?**

  - > Prose version (w images?)

  - > Video version



1.  Ms. Fr. 640 is available on the BnF’s repository Gallica,
    <https://gallica.bnf.fr/ark:/12148/btv1b10500001g.r=fr.%20640?rk=150215;2>.

2.  The Making and Knowing Project, <https://www.makingandknowing.org/>.

**Comment by ps2270** [comment]
Thanks, Tillmann. The "About" tile on the landing page will take you to this overview-about page, and this overview about page will simply have links and a 1-sentence explanation of each item on the About menu.
![image](https://user-images.githubusercontent.com/25156192/73123935-4d55c400-3f63-11ea-8752-e37508a4d2d8.png)

So, similar to the Overview of the Resources that you did yesterday:
![image](https://user-images.githubusercontent.com/25156192/73123946-6c545600-3f63-11ea-8340-5c280adb330b.png)

**Comment by TillmannTaape** [comment]
Thank you for clarifying!

**Comment by ps2270** [comment]
Changes to this page:
The Edition
CHANGE this:
The creation of Secrets of Craft and Nature in Renaissance France: collaborative transcription, translation, and encoding, historical research, and digital humanities.
to
The digital critical edition of Ms. Fr. 640, including its creation, structure, and features.

**Comment by TillmannTaape** [comment]
PHS changes implemented.

**Comment by njr2128** [comment]
done
